In [35]:
# import libraries
import pandas as pd
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch
import matplotlib.pyplot as plt
import random

# load the data
all_posts_df = pd.read_csv("../01_data/clean_data/all_posts_cleaned.csv")

In [2]:
# load the different models

# roberta model finetuned on German sentences in general
model_german_general = AutoModelForSequenceClassification.from_pretrained('ssary/XLM-RoBERTa-German-sentiment')
tokenizer_german_general = AutoTokenizer.from_pretrained('ssary/XLM-RoBERTa-German-sentiment')

In [3]:
# roberta model finetuned on German tweets
model_german_tweets = AutoModelForSequenceClassification.from_pretrained('cardiffnlp/xlm-roberta-base-tweet-sentiment-de')
tokenizer_german_tweets = AutoTokenizer.from_pretrained('cardiffnlp/xlm-roberta-base-tweet-sentiment-de')

# bert model by Oliver Guhr
from germansentiment import SentimentModel

In [36]:
# sample 250 posts
sampled_posts = all_posts_df.sample(n=250, random_state=20)[["text"]]

# create an empty column to store the label
sampled_posts["label"] = ""

# export to csv for manual labelling
sampled_posts.to_csv("../01_data/clean_data/posts_manual_labelling.csv")


In [21]:
for i in range(10):
    post = sampled_posts.iloc[i]
    inputs = tokenizer_german_general(post, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model_german_general(**inputs)
    predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
    sentiment_classes = ['negative', 'neutral', 'positive']
    print(sentiment_classes[predictions.argmax()]) # for the class with highest probability
    print(predictions)

neutral
tensor([[0.1373, 0.8435, 0.0192]])
neutral
tensor([[5.1459e-04, 9.9936e-01, 1.2992e-04]])
neutral
tensor([[1.1401e-05, 9.9997e-01, 1.5755e-05]])
positive
tensor([[0.0163, 0.1744, 0.8093]])
neutral
tensor([[0.0049, 0.9914, 0.0037]])
neutral
tensor([[0.2427, 0.7047, 0.0527]])
negative
tensor([[0.9809, 0.0095, 0.0096]])
neutral
tensor([[0.0031, 0.9938, 0.0030]])
neutral
tensor([[9.4581e-04, 9.9790e-01, 1.1509e-03]])
neutral
tensor([[0.0078, 0.9482, 0.0440]])
